### ISSUE TITLE
The plugin doesn't seem to work at the moment

### ISSUE THREAD

**Issue by nikitoss888** [vbalien/spicetify-extension-autoSkipPattern#2]
In some time already plugin doesn't do it's job despite unchanging and previously working pattern.
I've tested changing it and skipping back and forward to the song AND artist I didn't want to listen to, and even changed pattern for artists to a /.*/i, meaning it should skip everything.
Alas, I still have to skip manually. Using plugin on Windows 10 with Spicetify Marketplace, latest

**Comment by vbalien** [comment]
I've identified the issue and fixed it.
If you are still having issues, please reopen this issue. 
Thank you.
